
##############################################
# Settings for counter testbench
##############################################
---

# delimiters for parameter files
use_parameters: Yes
param_target_file: "rtl/custom/top.sv"
start_delimiter: "top #("
stop_delimiter: ")("

# override part of the parameters
override_parameters: Yes
override_param_target_file: "rtl/custom/top.sv"
override_param_file: "sim_params.txt"
override_start_delimiter: "  // -----------------------------------------------"
override_stop_delimiter: "  // -----------------------------------------------"
