
##############################################
# Odatix settings for simulations
##############################################
---

# overwrite existing results
overwrite:        No

# prompt 'Continue? (Y/n)' after settings checks
ask_continue:     Yes

# show simulation log if there is only one architecture selected
show_log_if_one:  Yes

# maximum number of parallel simulations
nb_jobs:          12

# targeted simulations
simulations: 

#--------------------------------------------#
# AsteRISC
#--------------------------------------------#

  - sim:
    - AsteRISC_RV32I_soc_crc_10S-10S/M0000

...
