#
# Copyright(C) 2022 by Jonathan Saussereau. All rights reserved.
# 
# All source codes and documentation contain proprietary confidential
# information and are distributed under license. It may be used, copied
# and/or disclosed only pursuant to the terms of a valid license agreement
# with Jonathan Saussereau. This copyright must be retained at all times.
#
# Makefile
#

TARGET = comparison
LIBS   = -lasterisc -ldebug -lgcc

all :
	@+$(MAKE) -f ../generic_makefile.mk TARGET=$(TARGET) LIBS="$(LIBS)" --no-print-directory
